# Generated by Django 3.0.8 on 2021-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20210516_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'benching my friend', 'verbose_name_plural': 'benching my friend'},
        ),
    ]
