# Generated by Django 3.0.8 on 2021-05-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20210518_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'make reservation here', 'verbose_name_plural': 'make reservation here'},
        ),
    ]
