# Generated by Django 3.0.8 on 2021-05-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bench8', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation8',
            options={'verbose_name': 'make reservation here', 'verbose_name_plural': 'make reservation here'},
        ),
    ]
