# Generated by Django 3.0.8 on 2021-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench9', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation9',
            options={'verbose_name': 'make reservation here', 'verbose_name_plural': 'make reservation here'},
        ),
        migrations.AlterField(
            model_name='reservation9',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
